export type UiLocale = 'id' | 'en'

const exactIdMap: Record<string, string> = {
  'Select option': 'Pilih opsi',
  'Selected': 'Dipilih',
  'No options': 'Tidak ada opsi',
  'Search...': 'Cari...',
  'Search attendance logs...': 'Cari log kehadiran...',
  'Select attendance date range': 'Pilih rentang tanggal kehadiran',
  'Select date range': 'Pilih rentang tanggal',
  'Active Employees': 'Karyawan Aktif',
  'Checked In': 'Sudah Check-in',
  'Checked Out': 'Sudah Check-out',
  'Pending Check In': 'Belum Check-in',
  'Pending Check Out': 'Belum Check-out',
  'Late Check In': 'Terlambat Check-in',
  'Check In': 'Check-in',
  'Check Out': 'Check-out',
  'Late check in': 'Terlambat check-in',
  'Missing check in': 'Tidak check-in',
  'Missing check out': 'Tidak check-out',
  'Browser timezone': 'Zona waktu browser',
  'Detecting...': 'Mendeteksi...',
  'Live': 'Langsung',
  'Mobile': 'Mobile',
  'Web': 'Web',
  'Recorded': 'Tercatat',
  'With Photo': 'Dengan Foto',
  'Without Photo': 'Tanpa Foto',
  'Missing Check In': 'Tidak Check-in',
  'Missing Check Out': 'Tidak Check-out',
  'No trend data is available yet for the selected period.': 'Belum ada data tren untuk periode yang dipilih.',
  'Team members who are missing attendance actions or checked in late.': 'Anggota tim yang belum melakukan aksi kehadiran atau check-in terlambat.',
  'Use the owner dashboard as the overview, then open resource pages for deeper operations.': 'Gunakan dashboard owner sebagai ringkasan, lalu buka halaman resource untuk operasi yang lebih dalam.',
  'Focus on arrival records for the selected day.': 'Fokus pada catatan kedatangan untuk hari yang dipilih.',
  'Manage employee profile and attendance assignments.': 'Kelola profil karyawan dan penugasan kehadiran.',
  'Review shift timing and grace periods.': 'Tinjau jadwal shift dan masa toleransi.',
  'The dashboard could not be refreshed just now. Please try again or inspect the attendance logs directly.': 'Dashboard tidak bisa dimuat ulang saat ini. Silakan coba lagi atau periksa log kehadiran secara langsung.',
  'Keep an eye on today’s attendance health, follow short-term trends, and jump into attendance logs when the team needs closer audit.': 'Pantau kondisi kehadiran hari ini, lihat tren jangka pendek, dan masuk ke log kehadiran saat tim perlu audit lebih detail.',
  'Pick a start date, then an end date.': 'Pilih tanggal mulai, lalu tanggal selesai.',
  'Clear': 'Hapus',
  'Close': 'Tutup',
  'Start': 'Mulai',
  'End': 'Selesai',
  'Attendance Logs': 'Log Kehadiran',
  'Employee No': 'No Karyawan',
  'Employee Name': 'Nama Karyawan',
  'Type': 'Tipe',
  'Source': 'Sumber',
  'Date': 'Tanggal',
  'Logged At': 'Dicatat Pada',
  'Photo Proof': 'Bukti Foto',
  'Available': 'Tersedia',
  'Advanced filters': 'Filter lanjutan',
  'Apply more specific conditions without changing the table layout.': 'Terapkan kondisi yang lebih spesifik tanpa mengubah tata letak tabel.',
  'Photo proof': 'Bukti foto',
  'All types': 'Semua tipe',
  'Search type...': 'Cari tipe...',
  'All sources': 'Semua sumber',
  'Search source...': 'Cari sumber...',
  'All photo states': 'Semua status foto',
  'Search photo state...': 'Cari status foto...',
  'Org unit': 'Unit organisasi',
  'All org units': 'Semua unit organisasi',
  'Search org unit...': 'Cari unit organisasi...',
  'Branch': 'Cabang',
  'All branches': 'Semua cabang',
  'Search branch...': 'Cari cabang...',
  'Work location': 'Lokasi kerja',
  'All work locations': 'Semua lokasi kerja',
  'Search work location...': 'Cari lokasi kerja...',
  'Reset all': 'Reset semua',
  'Done': 'Selesai',
  'Export format': 'Format ekspor',
  'Queueing...': 'Mengantrikan...',
  'Export queue': 'Antrean ekspor',
  'Export attendance logs': 'Ekspor log kehadiran',
  'Ready files': 'File siap',
  'In queue': 'Dalam antrean',
  'Current range': 'Rentang aktif',
  'Latest request': 'Permintaan terbaru',
  'No date range selected': 'Belum ada rentang tanggal',
  'Exports the current filtered attendance logs to XLSX.': 'Mengekspor log kehadiran sesuai filter aktif ke file XLSX.',
  'Refine attendance logs': 'Persempit log kehadiran',
  'Keep the primary filters visible and open advanced filters only when you need more precision.': 'Tampilkan filter utama dan buka filter lanjutan hanya saat butuh penyaringan lebih detail.',
  'Hide advanced filters': 'Sembunyikan filter lanjutan',
  'More filters': 'Filter lainnya',
  'Date range': 'Rentang tanggal',
  'Employee': 'Karyawan',
  'All employees': 'Semua karyawan',
  'Search employees...': 'Cari karyawan...',
  'Exception': 'Pengecualian',
  'All exceptions': 'Semua pengecualian',
  'Search exception...': 'Cari pengecualian...',
  'All statuses': 'Semua status',
  'Search status...': 'Cari status...',
  'Today': 'Hari Ini',
  'Yesterday': 'Kemarin',
  'This Week': 'Minggu Ini',
  'This Month': 'Bulan Ini',
  'Primary filters': 'Filter utama',
  'Quick ranges': 'Rentang cepat',
  'Use quick presets for common audit windows.': 'Gunakan preset cepat untuk rentang audit yang sering dipakai.',
  'Reset Filters': 'Reset Filter',
  'Active filters': 'Filter aktif',
  'Manage account details and role assignments in one place.': 'Kelola detail akun dan penugasan peran di satu tempat.',
  'Keep employee identity, assignment, and attendance setup aligned.': 'Jaga identitas, penugasan, dan pengaturan kehadiran karyawan tetap selaras.',
  'Define role naming and grade structure with a cleaner form layout.': 'Atur penamaan jabatan dan struktur grade dengan tata letak formulir yang lebih rapi.',
  'Set work location identity, timezone, and map coverage in one flow.': 'Atur identitas lokasi kerja, zona waktu, dan cakupan peta dalam satu alur.',
  'Organize shift timing and grace settings with a cleaner form layout.': 'Susun jam shift dan pengaturan toleransi dengan tata letak formulir yang lebih rapi.',
  'View Photo': 'Lihat Foto',
  'Attendance Log Detail': 'Detail Log Kehadiran',
  'Review the attendance record and its photo proof.': 'Tinjau catatan kehadiran dan bukti fotonya.',
  'Review the attendance record with a cleaner summary, supporting context, and photo proof.': 'Tinjau catatan kehadiran dengan ringkasan yang lebih rapi, konteks pendukung, dan bukti foto.',
  'Loading attendance detail...': 'Memuat detail kehadiran...',
  'Attendance Summary': 'Ringkasan Kehadiran',
  'Unknown Employee': 'Karyawan Tidak Dikenal',
  'Employee Information': 'Informasi Karyawan',
  'Who the attendance record belongs to.': 'Menunjukkan pemilik catatan kehadiran ini.',
  'Attendance Record': 'Catatan Kehadiran',
  'Main attendance activity and supporting notes.': 'Aktivitas kehadiran utama beserta catatan pendukung.',
  'Location Details': 'Detail Lokasi',
  'Address and coordinates captured when the log was created.': 'Alamat dan koordinat yang terekam saat log dibuat.',
  'Device Details': 'Detail Perangkat',
  'Device information used during the attendance submission.': 'Informasi perangkat yang digunakan saat mengirim kehadiran.',
  'System Metadata': 'Metadata Sistem',
  'Internal identifiers and timestamps for auditing.': 'Identifier internal dan cap waktu untuk kebutuhan audit.',
  'No data available in this section.': 'Tidak ada data yang tersedia pada bagian ini.',
  'Open Coordinates in Maps': 'Buka Koordinat di Peta',
  'Attendance Location Map': 'Peta Lokasi Kehadiran',
  'Use the photo to quickly verify that the record matches the employee submission.': 'Gunakan foto untuk memverifikasi dengan cepat bahwa catatan ini sesuai dengan kiriman karyawan.',
  'Photo Status': 'Status Foto',
  'Recorded Address': 'Alamat Terekam',
  'Device Name': 'Nama Perangkat',
  'Device ID': 'ID Perangkat',
  'Photo File ID': 'ID File Foto',
  'Created At': 'Dibuat Pada',
  'Updated At': 'Diperbarui Pada',
  'Attendance Log ID': 'ID Log Kehadiran',
  'Attendance Type': 'Tipe Kehadiran',
  'Loading photo...': 'Memuat foto...',
  'Open Full Size': 'Buka Ukuran Penuh',
  'No photo proof is attached to this attendance log.': 'Tidak ada bukti foto yang terlampir pada log kehadiran ini.',
  'Record Details': 'Detail Catatan',
  'Recent Exports': 'Ekspor Terbaru',
  'Exports follow the active filters at the time the request is created and will appear here once the file is ready to download.': 'Ekspor mengikuti filter aktif saat request dibuat dan akan muncul di sini ketika file siap diunduh.',
  'Refresh': 'Muat Ulang',
  'Loading recent exports...': 'Memuat ekspor terbaru...',
  'No export requests yet. Start one from the Export button above.': 'Belum ada permintaan ekspor. Mulai dari tombol Ekspor di atas.',
  'Requested': 'Diminta',
  'Started': 'Dimulai',
  'Completed': 'Selesai',
  'Expires': 'Kedaluwarsa',
  'Download': 'Unduh',
  'Generation failed': 'Pembuatan file gagal',
  'Waiting for file': 'Menunggu file',
  'Users': 'Pengguna',
  'Companies': 'Perusahaan',
  'Employees': 'Karyawan',
  'Work Locations': 'Lokasi Kerja',
  'Work Shifts': 'Shift Kerja',
  'Job Positions': 'Jabatan',
  'Roles & Permissions': 'Peran & Izin',
  'Owner Attendance Dashboard': 'Dashboard Kehadiran Owner',
  'Attendance Date': 'Tanggal Kehadiran',
  'Trend Window': 'Jendela Tren',
  'Attendance Trend': 'Tren Kehadiran',
  'Open Logs': 'Buka Log',
  'Checked in': 'Check-in',
  'Checked out': 'Check-out',
  'Late': 'Terlambat',
  'Missing checkout': 'Tidak check-out',
  'Needs Attention Today': 'Butuh Perhatian Hari Ini',
  'Audit Today': 'Audit Hari Ini',
  'No attendance exceptions for the selected day.': 'Tidak ada pengecualian kehadiran pada hari yang dipilih.',
  'First check in': 'Check-in pertama',
  'Last check out': 'Check-out terakhir',
  'Quick Actions': 'Aksi Cepat',
  'Check-in Records': 'Catatan Check-in',
  'Advanced filters active': 'Filter lanjutan aktif',
  'Filters active': 'Filter aktif',
  'Export': 'Ekspor',
  'Attendance export queued.': 'Ekspor kehadiran dimasukkan ke antrean.',
  'Attendance export queued as': 'Ekspor kehadiran dimasukkan antrean sebagai',
  'API Dashboard': 'Dashboard API',
  'Quick access to the main API resources.': 'Akses cepat ke resource API utama.',
  'Open': 'Buka',
  'Status': 'Status',
  'Name': 'Nama',
  'Full Name': 'Nama Lengkap',
  'Description': 'Deskripsi',
  'Address': 'Alamat',
  'Phone': 'Telepon',
  'City': 'Kota',
  'Capacity': 'Kapasitas',
  'Group': 'Grup',
  'Parent ID': 'ID Induk',
  'Organization Unit': 'Unit Organisasi',
  'Job Position': 'Jabatan',
  'Work Location': 'Lokasi Kerja',
  'Work Shift': 'Shift Kerja',
  'Join Date': 'Tanggal Bergabung',
  'Head coach': 'Pelatih kepala',
  'Timezone': 'Zona waktu',
  'Grace Period': 'Masa Toleransi',
  'Start Time': 'Jam Mulai',
  'End Time': 'Jam Selesai',
  'Grace Period (minutes)': 'Masa Toleransi (menit)',
  'Grade': 'Grade',
  'Category': 'Kategori',
  'Edit Organization Unit': 'Edit Unit Organisasi',
  'Parent Org Unit (Optional)': 'Unit Organisasi Induk (Opsional)',
  'First name': 'Nama depan',
  'Last name': 'Nama belakang',
  'Gender': 'Jenis kelamin',
  'Date of birth': 'Tanggal lahir',
  'Birth place': 'Tempat lahir',
  'Photo URL': 'URL Foto',
  'Blood type': 'Golongan darah',
  'Parent name': 'Nama orang tua',
  'Parent phone': 'Telepon orang tua',
  'Parent email': 'Email orang tua',
  'Emergency phone': 'Telepon darurat',
  'Medical notes': 'Catatan medis',
  'Birth date': 'Tanggal lahir',
  'Specialty': 'Spesialisasi',
  'Biography': 'Biografi',
  'Student': 'Siswa',
  'Program': 'Program',
  'Pricing': 'Harga',
  'Currency': 'Mata uang',
  'Billing cycle': 'Siklus penagihan',
  'Enrollment date': 'Tanggal pendaftaran',
  'Next payment date': 'Tanggal pembayaran berikutnya',
  'Loading...': 'Memuat...',
  'Cancel': 'Batal',
  'Saving...': 'Menyimpan...',
  'Create': 'Buat',
  'Update': 'Perbarui',
  'Edit': 'Ubah',
  'Add Work Shift': 'Tambah Shift Kerja',
  'Edit Work Shift': 'Ubah Shift Kerja',
  'Name is required': 'Nama wajib diisi',
  'Timezone is required': 'Zona waktu wajib diisi',
  'Start time is required': 'Jam mulai wajib diisi',
  'End time is required': 'Jam selesai wajib diisi',
  'Work shift created successfully': 'Shift kerja berhasil dibuat',
  'Work shift updated successfully': 'Shift kerja berhasil diperbarui',
  'Add Job Position': 'Tambah Jabatan',
  'Edit Job Position': 'Ubah Jabatan',
  'Job position created successfully': 'Jabatan berhasil dibuat',
  'Job position updated successfully': 'Jabatan berhasil diperbarui',
  'Add Employee': 'Tambah Karyawan',
  'Edit Employee': 'Ubah Karyawan',
  'Employee number is required': 'Nomor karyawan wajib diisi',
  'Full name is required': 'Nama lengkap wajib diisi',
  'Email is required': 'Email wajib diisi',
  'Work shift is required': 'Shift kerja wajib diisi',
  'Password must be at least 8 characters': 'Kata sandi minimal 8 karakter',
  'Select work shift': 'Pilih shift kerja',
  'Employee created successfully': 'Karyawan berhasil dibuat',
  'Employee updated successfully': 'Karyawan berhasil diperbarui',
  'Reset Password': 'Reset Kata Sandi',
  'Optional, min. 8 characters': 'Opsional, minimal 8 karakter',
  'Optional, leave blank to keep current password': 'Opsional, kosongkan untuk mempertahankan kata sandi saat ini',
  'Not assigned': 'Belum ditetapkan',
  'Select status': 'Pilih status',
  'Add User': 'Tambah Pengguna',
  'Edit User': 'Ubah Pengguna',
  'Username is required': 'Username wajib diisi',
  'Select at least one role': 'Pilih minimal satu peran',
  'User created successfully': 'Pengguna berhasil dibuat',
  'User updated successfully': 'Pengguna berhasil diperbarui',
  'Reset Password (Optional)': 'Reset Kata Sandi (Opsional)',
  'Minimum 8 characters': 'Minimal 8 karakter',
  'Leave blank to keep current password': 'Kosongkan untuk mempertahankan kata sandi saat ini',
  'Loading user data...': 'Memuat data pengguna...',
  'Roles': 'Peran',
  'Loading roles...': 'Memuat peran...',
  'No roles available.': 'Tidak ada peran tersedia.',
  'Selected roles': 'Peran terpilih',
  'None': 'Tidak ada',
  'Create User': 'Buat Pengguna',
  'Save Changes': 'Simpan Perubahan',
  'Create branch': 'Buat cabang',
  'Create category': 'Buat kategori',
  'Create program': 'Buat program',
  'Create student': 'Buat siswa',
  'Create teacher': 'Buat pengajar',
  'Create role': 'Buat peran',
  'Create enrollment': 'Buat enrollment',
  'Create Organization Unit': 'Buat Unit Organisasi',
  'Create new': 'Buat baru',
  'Loading org unit...': 'Memuat unit organisasi...',
  'Generate invoice': 'Buat invoice',
  'Creating...': 'Membuat...',
  'Permissions': 'Izin',
  'Page': 'Halaman',
  'Previous': 'Sebelumnya',
  'Role name': 'Nama peran',
  'Role description': 'Deskripsi peran',
  'Edit role': 'Ubah peran',
  'Search permissions': 'Cari izin',
  'No permissions found.': 'Tidak ada izin yang ditemukan.',
  'No permissions available.': 'Tidak ada izin yang tersedia.',
  'Failed to load permissions.': 'Gagal memuat izin.',
  'Role name is required.': 'Nama peran wajib diisi.',
  'Role created.': 'Peran berhasil dibuat.',
  'Role updated.': 'Peran berhasil diperbarui.',
  'Role id is missing.': 'ID peran tidak ditemukan.',
  'Permissions are managed by the backend and are read-only here.': 'Izin dikelola oleh backend dan hanya bisa dilihat di sini.',
  'Select timezone': 'Pilih zona waktu',
  'Search timezone': 'Cari zona waktu',
  'Use friendly timezone labels such as WIB, WITA, or WIT.': 'Gunakan label zona waktu yang lebih familiar seperti WIB, WITA, atau WIT.',
  'Set work location identity and map coverage in one flow.': 'Atur identitas lokasi kerja dan cakupan peta dalam satu alur.',
}

const tokenIdMap: Record<string, string> = {
  option: 'opsi',
  options: 'opsi',
  status: 'status',
  statuses: 'status',
  branch: 'cabang',
  branches: 'cabang',
  student: 'siswa',
  students: 'siswa',
  program: 'program',
  pricing: 'harga',
  type: 'tipe',
  types: 'tipe',
  source: 'sumber',
  sources: 'sumber',
  employee: 'karyawan',
  employees: 'karyawan',
  exception: 'pengecualian',
  exceptions: 'pengecualian',
  permission: 'izin',
  permissions: 'izin',
  limit: 'batas',
  'org unit': 'unit organisasi',
  'org units': 'unit organisasi',
  'work location': 'lokasi kerja',
  'work locations': 'lokasi kerja',
  'work shift': 'shift kerja',
  'work shifts': 'shift kerja',
  'job position': 'jabatan',
  'job positions': 'jabatan',
  gender: 'jenis kelamin',
  'blood type': 'golongan darah',
  'photo state': 'status foto',
  'photo states': 'status foto',
  billing: 'penagihan',
  branchs: 'cabang',
  language: 'bahasa',
  category: 'kategori',
  categories: 'kategori',
  role: 'peran',
  roles: 'peran',
}

const capitalize = (value: string) => value.charAt(0).toUpperCase() + value.slice(1)

const translateToken = (value: string) => {
  const normalized = value.trim().toLowerCase()
  return tokenIdMap[normalized] ?? exactIdMap[value.trim()] ?? null
}

export const localizeUiText = (locale: UiLocale, text: string): string => {
  if (locale !== 'id' || !text) {
    return text
  }

  const trimmed = text.trim()
  if (!trimmed) {
    return text
  }

  if (trimmed.endsWith(' *')) {
    return `${localizeUiText(locale, trimmed.slice(0, -2))} *`
  }

  if (trimmed.endsWith('*')) {
    return `${localizeUiText(locale, trimmed.slice(0, -1).trimEnd())} *`
  }

  const exact = exactIdMap[trimmed]
  if (exact) {
    return exact
  }

  const token = translateToken(trimmed)
  if (token) {
    return capitalize(token)
  }

  const dynamicPatterns: Array<[RegExp, (...matches: string[]) => string]> = [
    [/^(\d{4}-\d{2}-\d{2}) to (\d{4}-\d{2}-\d{2})$/, (from, to) => `${from} s.d. ${to}`],
    [/^Attendance overview for (.+)$/, date => `Ringkasan kehadiran untuk ${date}`],
    [/^Last (\d+) days$/, days => `${days} hari terakhir`],
    [/^Checked in, checked out, late check in, and missing check out counts for the last (\d+) days\.$/, days => `Jumlah check-in, check-out, keterlambatan, dan tidak check-out untuk ${days} hari terakhir.`],
    [/^Review detailed logs for (.+)\.$/, date => `Tinjau log detail untuk ${date}.`],
    [/^(\d+) advanced filters active$/, count => `${count} filter lanjutan aktif`],
    [/^(\d+) filters active$/, count => `${count} filter aktif`],
    [/^Attendance export queued as ([A-Z]+)\.$/, format => `Ekspor kehadiran dimasukkan antrean sebagai ${format}.`],
    [/^Export ([A-Z]+)$/, format => `Ekspor ${format}`],
  ]

  for (const [pattern, translate] of dynamicPatterns) {
    const match = trimmed.match(pattern)
    if (match) {
      return translate(...match.slice(1))
    }
  }

  const selectMatch = trimmed.match(/^Select (.+)$/)
  if (selectMatch) {
    const value = selectMatch[1] ?? ''
    const translated = translateToken(value) ?? value
    return `Pilih ${translated}`
  }

  const searchMatch = trimmed.match(/^Search (.+?)(\.\.\.)?$/)
  if (searchMatch) {
    const value = searchMatch[1] ?? ''
    const translated = translateToken(value) ?? value
    return `Cari ${translated}${searchMatch[2] ?? ''}`
  }

  const allMatch = trimmed.match(/^All (.+)$/)
  if (allMatch) {
    const value = allMatch[1] ?? ''
    const translated = translateToken(value) ?? value
    return `Semua ${translated}`
  }

  const lastDaysMatch = trimmed.match(/^Last (\d+) days$/)
  if (lastDaysMatch) {
    return `${lastDaysMatch[1]} hari terakhir`
  }

  return text
}
